namespace SwarmGrid.Domain.Entities;

/// <summary>
/// Edge device registration and status.
/// </summary>
public class Device : BaseEntity
{
    /// <summary>
    /// Unique device identifier (generated by edge agent).
    /// </summary>
    public required string DeviceId { get; set; }
    
    /// <summary>
    /// Hashed device secret for authentication.
    /// </summary>
    public required string DeviceSecretHash { get; set; }
    
    /// <summary>
    /// Tenant this device belongs to.
    /// </summary>
    public required string TenantId { get; set; }
    
    /// <summary>
    /// Site this device belongs to.
    /// </summary>
    public required string SiteId { get; set; }
    
    /// <summary>
    /// Associated camera ID (if applicable).
    /// </summary>
    public string? CameraId { get; set; }
    
    /// <summary>
    /// Device display name.
    /// </summary>
    public string? Name { get; set; }
    
    /// <summary>
    /// Current firmware/agent version.
    /// </summary>
    public string? AgentVersion { get; set; }
    
    /// <summary>
    /// Last known IP address.
    /// </summary>
    public string? IpAddress { get; set; }
    
    /// <summary>
    /// Last heartbeat timestamp.
    /// </summary>
    public DateTime? LastHeartbeat { get; set; }
    
    /// <summary>
    /// Device status.
    /// </summary>
    public DeviceStatus Status { get; set; } = DeviceStatus.Pending;
    
    /// <summary>
    /// Whether this device is active.
    /// </summary>
    public bool IsActive { get; set; } = true;
    
    /// <summary>
    /// Additional metadata (JSON).
    /// </summary>
    public string? MetadataJson { get; set; }
}

/// <summary>
/// Device status enumeration.
/// </summary>
public enum DeviceStatus
{
    /// <summary>
    /// Device registered but not yet approved.
    /// </summary>
    Pending = 0,
    
    /// <summary>
    /// Device is approved and active.
    /// </summary>
    Active = 1,
    
    /// <summary>
    /// Device is temporarily suspended.
    /// </summary>
    Suspended = 2,
    
    /// <summary>
    /// Device is revoked/deactivated.
    /// </summary>
    Revoked = 3
}
