using SwarmGrid.Domain.Enums;

namespace SwarmGrid.Domain.Entities;

/// <summary>
/// Risk event generated by Risk Engine.
/// </summary>
public class RiskEvent : BaseEntity
{
    public required string TenantId { get; set; }
    public required string SiteId { get; set; }
    public required string CameraId { get; set; }
    public required string ZoneId { get; set; }
    
    public double RiskScore { get; set; }
    public RiskLevel RiskLevel { get; set; }
    
    public List<string> SuggestedActions { get; set; } = [];
    
    // Acknowledgment
    public bool Acknowledged { get; set; }
    public string? AcknowledgedBy { get; set; }
    public DateTime? AcknowledgedAt { get; set; }
    
    // Source telemetry
    public Guid? SourceTelemetryId { get; set; }
}
