// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwarmGrid.Infrastructure.Data;

#nullable disable

namespace SwarmGrid.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SwarmGridDbContext))]
    [Migration("20260118132155_AddZonesTable")]
    partial class AddZonesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwarmGrid.Domain.Entities.RiskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Acknowledged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("acknowledged");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camera_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision")
                        .HasColumnName("risk_score");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_id");

                    b.Property<Guid?>("SourceTelemetryId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_telemetry_id");

                    b.Property<List<string>>("SuggestedActions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_actions");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_risk_events_created_at");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_risk_events_site_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_risk_events_zone_id");

                    b.HasIndex("SiteId", "CreatedAt")
                        .HasDatabaseName("ix_risk_events_site_created");

                    b.ToTable("risk_events", (string)null);
                });

            modelBuilder.Entity("SwarmGrid.Domain.Entities.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision")
                        .HasColumnName("progress");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sources_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sources_tenant_id");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("SwarmGrid.Domain.Entities.Telemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Alignment")
                        .HasColumnType("double precision")
                        .HasColumnName("alignment");

                    b.Property<double>("AvgSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_speed");

                    b.Property<double>("BottleneckIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("bottleneck_index");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camera_id");

                    b.Property<double>("Density")
                        .HasColumnType("double precision")
                        .HasColumnName("density");

                    b.Property<double>("FlowEntropy")
                        .HasColumnType("double precision")
                        .HasColumnName("flow_entropy");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_id");

                    b.Property<double>("SpeedVariance")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_variance");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_telemetries_timestamp");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_telemetries_zone_id");

                    b.HasIndex("ZoneId", "Timestamp")
                        .HasDatabaseName("ix_telemetries_zone_timestamp");

                    b.ToTable("telemetries", (string)null);
                });

            modelBuilder.Entity("SwarmGrid.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BottleneckPointsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CameraId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CameraIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PolygonJson")
                        .HasColumnType("jsonb");

                    b.Property<double>("RedThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("YellowThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("TenantId", "SiteId");

                    b.HasIndex("TenantId", "SiteId", "ZoneId")
                        .IsUnique();

                    b.ToTable("Zones", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
